# Generated by Django 3.1.6 on 2022-05-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('composition', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('purchasedPrice', models.FloatField(blank=True, null=True)),
                ('batchNo', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField()),
                ('expiryDate', models.DateField()),
                ('HSN', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('UPIid', models.CharField(max_length=100)),
                ('dlno', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('GSTNo', models.CharField(blank=True, max_length=100, null=True)),
                ('ownerName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('meds', models.ManyToManyField(blank=True, null=True, to='inventory.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='meds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicines'),
        ),
    ]
